version: '3.7'

services:
  standalone:
    image: apachepulsar/pulsar:2.7.1
    ports:
      - "8181:8080"
      - "6650:6650"
    volumes:
      - $HOME/workspace/pulsar-sample/data:/pulsar/data
      - $HOME/workspace/pulsar-sample/functions:/tmp/pulsar/functions
    environment:
      - BOOKIE_MEM=" -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    command: >
      /bin/bash -c
      "bin/apply-config-from-env.py conf/standalone.conf
      && bin/pulsar standalone --advertised-address 127.0.0.1"
